export const USER_REQUEST_CREATE_REQUEST = "USER_REQUEST_CREATE_REQUEST";
export const USER_REQUEST_CREATE_SUCCESS = "USER_REQUEST_CREATE_SUCCESS";
export const USER_REQUEST_CREATE_FAIL = "USER_REQUEST_CREATE_FAIL";
export const USER_REQUEST_CREATE_RESET = "USER_REQUEST_CREATE_RESET";
