export const USER_REQUEST_CREATE_REQUEST = "USER_REQUEST_CREATE_REQUEST";
export const USER_REQUEST_CREATE_SUCCESS = "USER_REQUEST_CREATE_SUCCESS";
export const USER_REQUEST_CREATE_FAIL = "USER_REQUEST_CREATE_FAIL";
export const USER_REQUEST_CREATE_RESET = "USER_REQUEST_CREATE_RESET";

export const USER_REQUEST_LIST_REQUEST = "USER_REQUEST_LIST_REQUEST";
export const USER_REQUEST_LIST_SUCCESS = "USER_REQUEST_LIST_SUCCESS";
export const USER_REQUEST_LIST_FAIL = "USER_REQUEST_LIST_FAIL";

export const USER_REQUEST_DETAILS_REQUEST = "USER_REQUEST_DETAILS_REQUEST";
export const USER_REQUEST_DETAILS_SUCCESS = "USER_REQUEST_DETAILS_SUCCESS";
export const USER_REQUEST_DETAILS_FAIL = "USER_REQUEST_DETAILS_FAIL";

export const USER_REQUEST_APPROVE_REQUEST = "USER_REQUEST_APPROVE_REQUEST";
export const USER_REQUEST_APPROVE_SUCCESS = "USER_REQUEST_APPROVE_SUCCESS";
export const USER_REQUEST_APPROVE_FAIL = "USER_REQUEST_APPROVE_FAIL";
export const USER_REQUEST_APPROVE_RESET = "USER_REQUEST_APPROVE_RESET";
